name: BattleGround
dependencies:
  - framework: "Carthage/Build/Device.xcframework"
  - framework: "Carthage/Build/Charts.xcframework"
  - framework: "Carthage/Build/RealmSwift.xcframework"
  - framework: "Carthage/Build/Realm.xcframework"